### ISSUE TITLE
[operator] Sync control plane and etcd config with EKS config

### ISSUE THREAD

**Issue by prateekgogia** [awslabs/kubernetes-iteration-toolkit#98]

**Comment by hakuna-matatah** [comment]
I see this issue is closed and the other issue regarding documentation is marked as a duplicate for this - https://github.com/awslabs/kubernetes-iteration-toolkit/issues/107

I'm wondering where is the documentation captured around the gap/differences  between etcd eks using etcd-manager (vs) kit. At least we need to document that to understand where KIT etcd stands w.r.t eks etcd and set the expectations for customer.
